version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Error handling
    - errcheck
    - errorlint

    # Code quality
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - unconvert

    # Complexity
    - gocyclo

    # Security
    - gosec

    # Best practices
    - revive
    - misspell
    - gocritic

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec

  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
    revive:
      rules:
        - name: var-naming
          disabled: true

formatters:
  enable:
    - gofmt
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
